apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lup-public-build-deploy-dev
  namespace: e8b9ad-tools
  labels:
    app: landuseplanning
    env: dev
    name: lup-public
spec:
  params: []
  resources: []
  workspaces: []
  tasks:
    - name: build-angular-builder
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build lup-public-angular-builder --follow --wait
    - name: build-nginx
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build lup-public-nginx-runtime --follow --wait
    - name: build-angular-compiled
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build-angular-builder
        - build-nginx
      params:
        - name: SCRIPT
          value: |
            oc start-build lup-public-compiled --follow --wait
    - name: build-deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build-angular-compiled
      params:
        - name: SCRIPT
          value: |
            oc start-build lup-public-deploy-image --follow --wait
    - name: deploy-to-dev
      params:
        - name: SCRIPT
          value: |
            oc tag lup-public-deploy-image:latest lup-public-deploy-image:dev
      runAfter:
        - build-deploy
      taskRef:
        kind: ClusterTask
        name: openshift-client
  finally:
    - name: push-to-teams-success
      params:
        - name: webhook-url
          value: # webhook url generated by MS Teams
        - name: webhook-payload
          value: # json format, using something from https://messagecardplayground.azurewebsites.net/ as a starter
      taskRef:
        kind: Task
        name: push-to-teams
      when:
        - input: $(tasks.status)
          operator: notin
          values:
            - Failed
    - name: push-to-teams-failure
      params:
        - name: webhook-url
          value: # webhook url generated by MS Teams
        - name: webhook-payload
          value: # json format, using something from https://messagecardplayground.azurewebsites.net/ as a starter
      taskRef:
        kind: Task
        name: push-to-teams
      when:
        - input: $(tasks.status)
          operator: in
          values:
            - Failed
