kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: lup-public-compiled
  namespace: e8b9ad-tools
  resourceVersion: '17127693008'
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'lup-public-compiled:latest'
  resources:
    limits:
      cpu: 500m
      memory: 4Gi
    requests:
      cpu: 400m
      memory: 2Gi
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'lup-public-angular-builder:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/bcgov/landuseplanning-public'
      ref: dev
    dockerfile: |-
      FROM image-registry.openshift-image-registry.svc:5000/e8b9ad-tools/lup-public-angular-builder:latest
      WORKDIR /opt/app-root/src
      COPY . .
      USER 0
      RUN chown -R 1001:0 /opt/app-root/src && chmod -R ug+rwx /opt/app-root/src
      USER 1001
      RUN npm install
      RUN mkdir -p /opt/app-root/scully && cp -r dist/scully/* /opt/app-root/scully/
  runPolicy: Serial