kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: lup-public-compiled
  namespace: e8b9ad-tools
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'lup-public-compiled:latest'
  resources:
    limits:
      cpu: 500m
      memory: 4Gi
    requests:
      cpu: 400m
      memory: 2Gi
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'lup-public-angular-builder:latest'
  postCommit:
    script: |
      mkdir -p /opt/app-root/scully && cp -r dist/scully/* /opt/app-root/scully/
  source:
    type: Git
    git:
      uri: 'https://github.com/bcgov/landuseplanning-public'
      ref: dev
  runPolicy: Serial