kind: Deployment
apiVersion: apps/v1
metadata:
  name: landuseplanning-public-dev
  namespace: e8b9ad-dev
  labels:
    app: landuseplanning-public-dev
    app.kubernetes.io/component: landuseplanning-public-dev
    app.kubernetes.io/instance: landuseplanning-public-dev
    app.kubernetes.io/part-of: landuseplanning-public-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: landuseplanning-public-dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: landuseplanning-public-dev
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            defaultMode: 420
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: lup-public-deploy-image
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 5
          env:
            - name: API_URL
              value: 'https://landuseplanning-dev.apps.silver.devops.gov.bc.ca/api'
            - name: REMOTE_API_PATH
              value: 'https://landuseplanning-dev.apps.silver.devops.gov.bc.ca/api/public'
            - name: REMOTE_API_BASE_PATH
              value: 'https://landuseplanning-dev.apps.silver.devops.gov.bc.ca/api'
            - name: REMOTE_ADMIN_PATH
              value: 'https://landuseplanning-dev.apps.silver.devops.gov.bc.ca/admin'
            - name: DEPLOYMENT_ENVIRONMENT
              value: dev
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          terminationMessagePolicy: File
          image: image-registry.apps.silver.devops.gov.bc.ca/e8b9ad-tools/lup-public-deploy-image
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
